# Generated by Django 4.1.5 on 2023-01-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order', models.IntegerField()),
                ('status_choices', models.TextField(choices=[('Shipped from warehouse', 'Shipped'), ('Received at warehouse', 'Received'), ('Not received', 'Pending')], default='Not received')),
                ('customer_name', models.TextField()),
                ('equipment_cost', models.IntegerField()),
                ('final_destination', models.TextField()),
                ('internal_contacts', models.TextField()),
                ('product_description', models.TextField()),
                ('inbound_carrier', models.TextField()),
                ('inbound_tracking', models.TextField()),
                ('num_pallets', models.IntegerField()),
                ('num_boxes', models.IntegerField()),
                ('dimensions', models.TextField()),
                ('weight', models.IntegerField()),
                ('lithium', models.TextField()),
                ('serial_num', models.IntegerField()),
                ('country_origin', models.TextField()),
                ('outbound_carrier', models.TextField()),
                ('outbound_tracking', models.TextField()),
                ('out_pallets', models.IntegerField()),
                ('out_boxes', models.IntegerField()),
            ],
        ),
    ]
