# Generated by Django 4.1.5 on 2023-01-05 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseorders',
            name='date_received',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='warehouseorders',
            name='date_shipped',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
