# Generated by Django 4.1.5 on 2023-01-05 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehouseorders_date_received_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseorders',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='warehouseorders',
            name='height',
            field=models.IntegerField(default=10, verbose_name='Height (in inches)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouseorders',
            name='length',
            field=models.IntegerField(default=10, verbose_name='Length (in inches)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouseorders',
            name='width',
            field=models.IntegerField(default=10, verbose_name='Width (in inches)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='country_origin',
            field=models.TextField(verbose_name='Country of Origin'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='customer_name',
            field=models.TextField(verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='date_received',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Received by Warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='date_shipped',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Shipped From Warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='equipment_cost',
            field=models.IntegerField(verbose_name='Cost of Equipment'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='final_destination',
            field=models.TextField(verbose_name='Final Destination'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='inbound_carrier',
            field=models.TextField(verbose_name='Incoming Carrier Name'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='inbound_tracking',
            field=models.TextField(verbose_name='Incoming Tracking Number'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='internal_contacts',
            field=models.TextField(verbose_name='Internal Contacts'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='lithium',
            field=models.TextField(verbose_name='Lithium Battery Sticker Present'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='num_boxes',
            field=models.IntegerField(verbose_name='Number of boxes Received'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='num_pallets',
            field=models.IntegerField(verbose_name='Number of Pallets Received'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='out_boxes',
            field=models.IntegerField(verbose_name='Number of Boxes Shipped'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='out_pallets',
            field=models.IntegerField(verbose_name='Number of Pallets Shipped'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='outbound_carrier',
            field=models.TextField(verbose_name='Outgoing Carrier Name'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='outbound_tracking',
            field=models.TextField(verbose_name='Outgoing Tracking Number'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='product_description',
            field=models.TextField(verbose_name='Short Description of Order'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='sales_order',
            field=models.IntegerField(verbose_name='Sales Order Number'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='serial_num',
            field=models.TextField(verbose_name='Serial Numbers'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='status_choices',
            field=models.TextField(choices=[('Shipped from warehouse', 'Shipped'), ('Received at warehouse', 'Received'), ('Not received', 'Pending')], default='Not received', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='warehouseorders',
            name='weight',
            field=models.IntegerField(verbose_name='Weight (in pounds)'),
        ),
    ]
