# Generated by Django 4.1.5 on 2023-01-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_warehouseorders_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorders',
            name='date_received',
            field=models.DateField(auto_now_add=True, verbose_name='Date Received by Warehouse'),
        ),
    ]
